name: Build and Deploy Demo Site

on:
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy_demo_site:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    env:
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: jekyll/minima
          ref: demo-site
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Clone target branch
        run: |
          REMOTE_BRANCH="${REMOTE_BRANCH:-gh-pages}"
          REMOTE_REPO="https://${GITHUB_ACTOR}:${{'${{'}} secrets.GITHUB_TOKEN ${{'}}'}}@github.com/${GITHUB_REPOSITORY}.git"

          echo "Publishing to ${GITHUB_REPOSITORY} on branch ${REMOTE_BRANCH}"
          rm -rf _site/
          git clone --depth=1 --branch="${REMOTE_BRANCH}" --single-branch --no-checkout "${REMOTE_REPO}" _site/
      - name: Build site
        run: bundle exec jekyll build --verbose --trace
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          
      - name: Configure GitHub Pages
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.updateInformationAboutPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              source: {
                branch: 'gh-pages',
                path: '/blog'
              }
            })

